<?php

/**
 * @file
 * Provides an media entity browser with a folder structure.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Component\Serialization\Yaml;

/**
 * Implements hook_entity_base_field_info().
 */
function media_folder_browser_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];

  // Add a 'Parent folder' base field to all selected media types.
  if ($entity_type->id() === 'media') {

    $fields['field_parent_folder'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('Parent folder'))
      ->setDescription(t('The parent folder of this entity.'))
      ->setSetting('target_type', 'folder_entity')
      ->setSetting('handler', 'default');
  }

  return $fields;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function media_folder_browser_preprocess_folder_browser_folder_item(&$variables) {
  $image = drupal_get_path('module', 'media_folder_browser') . '/assets/folder-big.svg';
  $variables['folder_icon'] = base_path() . $image;
}

/**
 * Implements hook_theme().
 */
function media_folder_browser_theme($existing, $type, $theme, $path) {
  $themes = Yaml::decode(file_get_contents(DRUPAL_ROOT . '/' . $path . '/' . $theme . '.themes.yml'));
  return $themes !== NULL ? $themes : [];
}